name: Lint Commit Messages

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  commitlint:
    name: commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          # commitlint needs the full history to find the range of commits
          # introduced by the pull request.
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # v6
